# Use the official Node.js image as the base image
FROM node:20.9

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

WORKDIR /server

RUN npm run prepare
# Install dependencies

RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 7000

# Command to run the application
CMD ["npm", "build"]